import TabDisplay from "@/src/components/TabDisplay";
import CardGrid from "@/src/components/CardGrid";
import MediaCardMUI from "@/src/components/MediaCardMUI";
import { Movie, TV } from "@/src/lib/interface";

interface TVCredits {
  cast?: TV[];
  crew?: TV[];
  id: number;
}
interface MovieCredits {
  cast?: Movie[];
  crew?: Movie[];
  id: number;
}

const fetchData = async (mediaType: string, id: string) => {
  const tmdbKey = process.env.MOVIE_DB_API;
  const url = `https://api.themoviedb.org/3/${mediaType}/${id}?api_key=${tmdbKey}&language=en-US`;
  const result = await fetch(url, { next: { revalidate: 28800 } });
  return result.json();
};

const fetchMovieCredits = async (id: string): Promise<MovieCredits> => {
  const tmdbKey = process.env.MOVIE_DB_API;
  const url = `https://api.themoviedb.org/3/person/${id}/movie_credits?api_key=${tmdbKey}&language=en-US`;
  const result = await fetch(url, { next: { revalidate: 28800 } });
  return result.json();
};

const fetchTVCredits = async (id: string): Promise<TVCredits> => {
  const tmdbKey = process.env.MOVIE_DB_API;
  const url = `https://api.themoviedb.org/3/person/${id}/tv_credits?api_key=${tmdbKey}&language=en-US`;
  const result = await fetch(url, { next: { revalidate: 28800 } });
  return result.json();
};

const PersonPage = async () => {
  const data = await fetchData("person", "976");
  const movieCredits = await fetchMovieCredits("976");
  const tvCredits = await fetchTVCredits("976");

  function consolidateMedia(media: (Movie | TV)[], type: "movie" | "tv") {
    interface Tracker {
      [id: string]: number;
    }
    const hashmap: Tracker = {};
    let result = [];

    for (let each of media) {
      if (!hashmap[each.id]) {
        hashmap[each.id] = 1;
        const mediaData = each as Movie & TV; //type assertion
        const media = {
          poster_path: mediaData.poster_path,
          title: mediaData.title ?? mediaData.name,
          vote_average: mediaData.vote_average,
          release_date: mediaData.release_date ?? mediaData.first_air_date,
          id: mediaData.id,
          media_type: type,
        };
        if (media.release_date) result.push(media); //some entries don't have a release date so we cut them out
      }
    }
    return result;
  }

  const handleCredits = (credits: MovieCredits | TVCredits, type: "movie" | "tv") => {
    let cast: (Movie | TV)[] = [];
    let crew: (Movie | TV)[] = [];

    if (credits.cast) {
      cast = credits.cast;
    }

    if (credits.crew) {
      crew = credits.crew;
    }

    const mediaArray = consolidateMedia([...cast, ...crew], type);

    mediaArray.sort((a, b) => {
      const dateA = parseInt(a.release_date.slice(0, 4));
      const dateB = parseInt(b.release_date.slice(0, 4));
      return dateB - dateA;
    });

    return mediaArray;
  };

  const consolidatedMovies = handleCredits(movieCredits, "movie");
  const consolidatedTV = handleCredits(tvCredits, "tv");

  return (
    <main>
      <TabDisplay tabNames={["Bio", "Movies", "TV"]}>
        <div>{JSON.stringify(data, null, 2)}</div>
        <CardGrid>
          {consolidatedMovies.map(media => (
            <MediaCardMUI media={media} />
          ))}
        </CardGrid>
        <CardGrid>
          {consolidatedTV.map(media => (
            <MediaCardMUI media={media} />
          ))}
        </CardGrid>
      </TabDisplay>
    </main>
  );
};

export default PersonPage;

const result = {
  adult: false,
  also_known_as: ["Джейсон Стейтем", "Джейсон Стэйтем", "جيسون ستاثام", "ジェイソン・ステイサム", "เจสัน สเตธัม", "傑森·史塔森", "Джейсън Стейтъм", "ჯეისონ სტეტჰემი", "Τζέισον Στέιθαμ", "JS", "杰森·斯坦森", "제이슨 스타뎀", "جیسون استاتهام"],
  biography:
    "Jason Statham (born 26 July 1967) is an English actor. He is known for portraying characters in various action-thriller films who are typically tough, hardboiled, gritty, or violent.\n\nStatham began practising Chinese martial arts, kickboxing, and karate recreationally in his youth while working at local market stalls. An avid footballer and diver, he was a member of Britain's national diving team and competed for England in the 1990 Commonwealth Games. Shortly after, he was asked to model for French Connection, Tommy Hilfiger, and Levi's in various advertising campaigns. His past history working at market stalls inspired his casting in the Guy Ritchie crime films Lock, Stock and Two Smoking Barrels (1998) and Snatch (2000).\n\nThe commercial success of these films led Statham to star as Frank Martin in the Transporter trilogy (2002–2008). After starring in a variety of heist and action-thriller films such as The Italian Job (2003), Crank (2006), War (2007), The Bank Job (2008), The Mechanic (2011), Spy (2015), and Mechanic: Resurrection (2016), he established himself as a Hollywood leading man. However, he has also starred in commercially and critically unsuccessful films such as Revolver (2005), Chaos (2005), In the Name of the King (2007), 13 (2010), Blitz (2011), Killer Elite (2011), Hummingbird (2013), and Wild Card (2015). He regained commercial success as a part of the ensemble action series The Expendables (2010–2014) and the Fast & Furious franchise. In the latter, he has played Deckard Shaw in Fast & Furious 6 (2013), Furious 7 (2015), The Fate of the Furious (2017), F9 (2021) and the spin-off Fast & Furious Presents: Hobbs & Shaw (2019). He was credited as a co-producer on Hobbs & Shaw, receiving his first production credit.\n\nStatham's acting has been criticised for lacking depth and variety, but he has also been praised for leading the resurgence of action films during the 2000s and 2010s. According to a BBC News report, his film career from 2002 to 2017 generated an estimated $1.5 billion (£1.1 billion) in ticket sales, making him one of the film industry's most bankable stars.",
  birthday: "1967-07-26",
  deathday: null,
  gender: 2,
  homepage: null,
  id: 976,
  imdb_id: "nm0005458",
  known_for_department: "Acting",
  name: "Jason Statham",
  place_of_birth: "Shirebrook, Derbyshire, England, UK",
  popularity: 95.729,
  profile_path: "/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg",
};

const movies = {
  cast: [
    {
      adult: false,
      backdrop_path: "/ysKahAEPP8h6MInuLjr0xuZOTjh.jpg",
      genre_ids: [80, 35],
      id: 107,
      original_language: "en",
      original_title: "Snatch",
      overview: "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
      popularity: 34.679,
      poster_path: "/56mOJth6DJ6JhgoE2jtpilVqJO.jpg",
      release_date: "2000-09-01",
      title: "Snatch",
      video: false,
      vote_average: 7.803,
      vote_count: 8113,
      character: "Turkish",
      credit_id: "52fe4218c3a36847f8003be1",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/kSTvteM3ekuoeO7u7GJtZQkZuom.jpg",
      genre_ids: [28, 53, 80],
      id: 1948,
      original_language: "en",
      original_title: "Crank",
      overview:
        "Chev Chelios, a hit man wanting to go straight, lets his latest target slip away. Then he awakes the next morning to a phone call that informs him he has been poisoned and has only an hour to live unless he keeps adrenaline coursing through his body while he searches for an antidote.",
      popularity: 24.393,
      poster_path: "/toaY9CoMAy37QNv8HbbUqWS4X1Q.jpg",
      release_date: "2006-08-31",
      title: "Crank",
      video: false,
      vote_average: 6.631,
      vote_count: 3308,
      character: "Chev Chelios",
      credit_id: "52fe4325c3a36847f803dc2b",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/jj6II1bSyJI1WsBWGWxv9AKeGH8.jpg",
      genre_ids: [12, 14, 28, 18],
      id: 2312,
      original_language: "en",
      original_title: "In the Name of the King: A Dungeon Siege Tale",
      overview: "A man named Farmer sets out to rescue his kidnapped wife and avenge the death of his son -- two acts committed by the Krugs, a race of animal-warriors who are controlled by the evil Gallian.",
      popularity: 18.919,
      poster_path: "/bbN1lmDk1PT0GsTFCy179sk5nIF.jpg",
      release_date: "2007-11-29",
      title: "In the Name of the King: A Dungeon Siege Tale",
      video: false,
      vote_average: 4.7,
      vote_count: 736,
      character: "Farmer",
      credit_id: "52fe434dc3a36847f8049e1d",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/5mbFEJStH59cNFcF7VkRgsSxMqK.jpg",
      genre_ids: [28, 53, 878],
      id: 10483,
      original_language: "en",
      original_title: "Death Race",
      overview:
        "Terminal Island, New York: 2020. Overcrowding in the US penal system has reached a breaking point. Prisons have been turned over to a monolithic Weyland Corporation, which sees jails full of thugs as an opportunity for televised sport. Adrenalized inmates, a global audience hungry for violence and a spectacular, enclosed arena come together to form the 'Death Race', the biggest, most brutal event.",
      popularity: 29.268,
      poster_path: "/5A79GeOb3uChQ0l0ZDjDyODKQp3.jpg",
      release_date: "2008-08-22",
      title: "Death Race",
      video: false,
      vote_average: 6.245,
      vote_count: 3398,
      character: "Jensen Ames",
      credit_id: "52fe43789251416c75011ac3",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg",
      genre_ids: [28, 80, 53],
      id: 4108,
      original_language: "en",
      original_title: "The Transporter",
      overview:
        "Former Special Forces officer, Frank Martin will deliver anything to anyone for the right price, and his no-questions-asked policy puts him in high demand. But when he realizes his latest cargo is alive, it sets in motion a dangerous chain of events. The bound and gagged Lai is being smuggled to France by a shady American businessman, and Frank works to save her as his own illegal activities are uncovered by a French detective.",
      popularity: 34.162,
      poster_path: "/v3QIFUWgtVN4wejVuDZowuyJ20W.jpg",
      release_date: "2002-10-02",
      title: "The Transporter",
      video: false,
      vote_average: 6.687,
      vote_count: 4789,
      character: "Frank Martin",
      credit_id: "52fe43adc3a36847f806714f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/1RQqmTLtJBQWIGXsWzuuJsY0gCu.jpg",
      genre_ids: [18, 53, 80, 9648],
      id: 10851,
      original_language: "en",
      original_title: "Revolver",
      overview:
        "Hotshot gambler Jake Green is long on bravado and seriously short of common sense. Rarely is he allowed in any casino because he's a bona fide winner and, in fact, has taken so much money over the years that he's the sole client of his accountant elder brother, Billy. Invited to a private game, Jake is in fear of losing his life.",
      popularity: 17.435,
      poster_path: "/cXJYFEIGNxiNTCekP1A68ICzJen.jpg",
      release_date: "2005-09-11",
      title: "Revolver",
      video: false,
      vote_average: 6.385,
      vote_count: 1195,
      character: "Jake Green",
      credit_id: "52fe43c39251416c7501d26d",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/rR8c2J0i8j9tEjacHE8xgEDPDUS.jpg",
      genre_ids: [18, 28, 80],
      id: 5289,
      original_language: "en",
      original_title: "Chaos",
      overview:
        "In Seattle, detective Quentin Conners is unfairly suspended and his partner Jason York leaves the police force after a tragic shooting on Pearl Street Bridge, when the hostage and the criminal die. During a bank heist with a hostage situation, Conners is assigned in charge of the operation with the rookie Shane Dekker as his partner. The thieves, lead by Lorenz, apparently do not steal a penny from the bank. While chasing the gangsters, the police team disclose that they planted a virus in the system, stealing one billion dollars from the different accounts, using the principle of the Chaos Theory. Further, they find that Lorenz is killing his accomplices.",
      popularity: 13.995,
      poster_path: "/oOQ3PS8wp5Iezqc5LChOq2S97Jl.jpg",
      release_date: "2005-01-17",
      title: "Chaos",
      video: false,
      vote_average: 6.307,
      vote_count: 909,
      character: "Det. Quentin Conners",
      credit_id: "52fe4402c3a36847f807d077",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/ynnarxTMs8jWKV9GK0SpUhGNCgH.jpg",
      genre_ids: [53, 80, 18],
      id: 8848,
      original_language: "en",
      original_title: "The Bank Job",
      overview:
        "Terry is a small-time car dealer trying to leave his shady past behind and start a family. Martine is a beautiful model from Terry's old neighbourhood who knows that Terry is no angel. When Martine proposes a foolproof plan to rob a bank, Terry recognises the danger but realises this may be the opportunity of a lifetime. As the resourceful band of thieves burrows its way into a safe-deposit vault at a Lloyds Bank, they quickly realise that, besides millions in riches, the boxes also contain secrets that implicate everyone from London's most notorious underworld gangsters to powerful government figures, and even the Royal Family. Although the heist makes headlines throughout Britain for several days, a government gag order eventually brings all reporting of the case to an immediate halt.",
      popularity: 23.653,
      poster_path: "/ayrGDJDsSBczjztGUWKqmzL97xg.jpg",
      release_date: "2008-02-28",
      title: "The Bank Job",
      video: false,
      vote_average: 6.821,
      vote_count: 2013,
      character: "Terry Leather",
      credit_id: "52fe44c0c3a36847f80a7f49",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/ghgogVFRi60o0sVsRWgpG2r4Sy9.jpg",
      genre_ids: [28, 53, 80],
      id: 9335,
      original_language: "en",
      original_title: "Transporter 2",
      overview:
        "Professional driver Frank Martin is living in Miami, where he is temporarily filling in for a friend as the chauffeur for a government narcotics control policymaker and his family. The young boy in the family is targeted for kidnapping, and Frank immediately becomes involved in protecting the child and exposing the kidnappers.",
      popularity: 35.624,
      poster_path: "/cdm17vK8PxHfTi7ayZf6WKbOgUO.jpg",
      release_date: "2005-08-03",
      title: "Transporter 2",
      video: false,
      vote_average: 6.309,
      vote_count: 3200,
      character: "Frank Martin",
      credit_id: "52fe44e9c3a36847f80b1521",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/dYb6kgvoGjUH59n2uB4eV9xqmKR.jpg",
      genre_ids: [28, 53, 80],
      id: 27582,
      original_language: "en",
      original_title: "The Mechanic",
      overview:
        "Arthur Bishop is a 'mechanic' - an elite assassin with a strict code and unique talent for cleanly eliminating targets. It's a job that requires professional perfection and total detachment, and Bishop is the best in the business. But when he is ordered to take out his mentor and close friend Harry, Bishop is anything but detached.",
      popularity: 38.592,
      poster_path: "/k37axEHszFP9WOVvbozxF0r7X7g.jpg",
      release_date: "2011-01-13",
      title: "The Mechanic",
      video: false,
      vote_average: 6.485,
      vote_count: 2872,
      character: "Arthur Bishop",
      credit_id: "52fe4556c3a368484e0543fb",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/nNbxrSyKUTMVwpnFgnKH9ZV0QZ8.jpg",
      genre_ids: [28, 12, 53, 80],
      id: 13387,
      original_language: "en",
      original_title: "Transporter 3",
      overview:
        "Frank Martin puts the driving gloves on to deliver Valentina, the kidnapped daughter of a Ukranian government official, from Marseilles to Odessa on the Black Sea. En route, he has to contend with thugs who want to intercept Valentina's safe delivery and not let his personal feelings get in the way of his dangerous objective.",
      popularity: 35.63,
      poster_path: "/o4w9VF3GRZuXe9NHHvZ07pJespl.jpg",
      release_date: "2008-11-26",
      title: "Transporter 3",
      video: false,
      vote_average: 6.139,
      vote_count: 3033,
      character: "Frank Martin",
      credit_id: "52fe45639251416c75054a6b",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/4K57Vd78y3pMsAAfOdZYATTqnL3.jpg",
      genre_ids: [28, 53, 80],
      id: 15092,
      original_language: "en",
      original_title: "Crank: High Voltage",
      overview: "Chelios faces a Chinese mobster who has stolen his nearly indestructible heart and replaced it with a battery-powered ticker that requires regular jolts of electricity to keep working.",
      popularity: 50.755,
      poster_path: "/tzTC4EEvF0OPL63frEiogxL2T8M.jpg",
      release_date: "2009-04-16",
      title: "Crank: High Voltage",
      video: false,
      vote_average: 6.042,
      vote_count: 2521,
      character: "Chev Chelios",
      credit_id: "52fe46389251416c7507132b",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/boET2fgExdaOfojez5VKQqAoKAs.jpg",
      genre_ids: [99],
      id: 16900,
      original_language: "en",
      original_title: "Truth In 24",
      overview:
        "It's 24 hours of pure exhilaration, complete exhaustion, and it's not for the faint of heart or the ill-prepared. It is the legendary 24 Hours of Le Mans. But before you win it, you have to master finishing it. This film chronicles the dedication, the determination and the spirit required to not just survive 3,000 grueling miles, but to be in a position to win one of the greatest races in history.",
      popularity: 4.585,
      poster_path: "/wLiHPyV6yUhBWUL3iX0TZMMkSQg.jpg",
      release_date: "2008-11-06",
      title: "Truth In 24",
      video: false,
      vote_average: 7.2,
      vote_count: 13,
      character: "Narrator",
      credit_id: "52fe46f59251416c750892e5",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/RzIuQRoXiO8WeFdjtnjUCzSymV.jpg",
      genre_ids: [28, 12, 53],
      id: 49021,
      original_language: "en",
      original_title: "Killer Elite",
      overview:
        "Based on a shocking true story, Killer Elite pits two of the world’s most elite operatives—Danny, an ex-special ops agent and Hunter, his longtime mentor—against the cunning leader of a secret military society. Covering the globe from Australia to Paris, London and the Middle East, Danny and Hunter are plunged into a highly dangerous game of cat and mouse—where the predators become the prey.",
      popularity: 16.45,
      poster_path: "/7O2U0WPFPSvNSUYZlhbnV081lBF.jpg",
      release_date: "2011-09-22",
      title: "Killer Elite",
      video: false,
      vote_average: 6.263,
      vote_count: 1908,
      character: "Danny",
      credit_id: "52fe4781c3a36847f81396f9",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/sNtRc8pq28UBjzcl0ty556UbDoO.jpg",
      genre_ids: [28, 80, 53],
      id: 72387,
      original_language: "en",
      original_title: "Safe",
      overview: "After a former elite agent rescues a 12-year-old Chinese girl who's been abducted, they find themselves in the middle of a standoff between Triads, the Russian Mafia and high-level corrupt New York City politicians and police.",
      popularity: 44.023,
      poster_path: "/kOCpkoMUVae9UIf85gO71SyjLbW.jpg",
      release_date: "2012-04-16",
      title: "Safe",
      video: false,
      vote_average: 6.47,
      vote_count: 2178,
      character: "Luke Wright",
      credit_id: "52fe4868c3a368484e0f714f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/tg4IgDUIP2FPAMHZIMo9UQSKoBS.jpg",
      genre_ids: [80, 28, 53],
      id: 55846,
      original_language: "en",
      original_title: "Blitz",
      overview: "A tough cop is dispatched to take down a serial killer who has been targeting police officers.",
      popularity: 33.933,
      poster_path: "/qjqmhhc7uLub22mhu4V6DjOBwXM.jpg",
      release_date: "2011-05-20",
      title: "Blitz",
      video: false,
      vote_average: 6.2,
      vote_count: 1474,
      character: "Tom Brant",
      credit_id: "52fe48e2c3a36847f817ea43",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/xO21Nwgzu3ssa9L5zhTWCxGcSE9.jpg",
      genre_ids: [99],
      id: 111192,
      original_language: "en",
      original_title: "Truth In 24 II: Every Second Counts",
      overview:
        "The film TRUTH IN 24 II documents the tenth and arguably most emotional triumph of the brand with the four rings at this sports car classic. After two Audi R18 TDI cars have retired following spectacular accidents, the remaining Audi fights a dramatic battle for overall victory with the three Peugeot 908 cars which the Audi trio ultimately decides in its favor with a narrow margin of 13 seconds. The film captures the entire drama of the fourth-narrowest running of the Le Mans 24 Hours with intimate insights into the team of Audi Sport and breath-taking pictures.",
      popularity: 3.007,
      poster_path: "/7sycIw5sg6zqHzdI8DColwDjTdI.jpg",
      release_date: "2012-05-22",
      title: "Truth In 24 II: Every Second Counts",
      video: false,
      vote_average: 7,
      vote_count: 11,
      character: "Narrator",
      credit_id: "52fe4af3c3a36847f81ea161",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/qGtuuNro6M8Q3VFvmGJwFkg9bns.jpg",
      genre_ids: [28, 80],
      id: 119283,
      original_language: "en",
      original_title: "Parker",
      overview:
        "A thief with a unique code of professional ethics is double-crossed by his crew and left for dead. Assuming a new disguise and forming an unlikely alliance with a woman on the inside, he looks to hijack the score of the crew's latest heist.",
      popularity: 27.063,
      poster_path: "/u1cl4RsdqMjolVVsHwiLRPN1CT2.jpg",
      release_date: "2013-01-23",
      title: "Parker",
      video: false,
      vote_average: 6.016,
      vote_count: 2769,
      character: "Parker",
      credit_id: "52fe4bfac3a36847f821baad",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/lLZdvnt25Jg5R9Cece3EYKnTsrW.jpg",
      genre_ids: [28, 53],
      id: 136418,
      original_language: "en",
      original_title: "Hummingbird",
      overview:
        "Homeless and on the run from a military court martial, a damaged ex-special forces soldier navigating London's criminal underworld seizes an opportunity to assume another man's identity, transforming into an avenging angel in the process.",
      popularity: 30.03,
      poster_path: "/bN2aGUOxHRwGms68WTDr2MHzkKa.jpg",
      release_date: "2013-05-07",
      title: "Hummingbird",
      video: false,
      vote_average: 6.176,
      vote_count: 1518,
      character: "Joey Jones",
      credit_id: "52fe4c16c3a368484e1a63ed",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/39XzlXJRGMdHGGtHJ3VlCRfRRin.jpg",
      genre_ids: [28, 53],
      id: 204082,
      original_language: "en",
      original_title: "Homefront",
      overview:
        "Phil Broker is a former DEA agent who has gone through a crisis after his action against a biker gang went horribly wrong and it cost the life of his boss' son. He is recently widowed and is left with a 9-years-old daughter, Maddy. He decides to quit the turbulent and demanding life of thrill for Maddy's sake and retires to a small town. His daughter fights off a boy who was bullying her at school and this sets in motion a round of events that end in his direct confrontation with the local Meth drug lord. His past history with the biker gang also enters the arena, making matters more complex. But he has a mission in his mind to protect his daughter and he is ready to pay any cost that it demands.",
      popularity: 27.657,
      poster_path: "/v55tfjL3QGeabkXAMXPb4olwjL0.jpg",
      release_date: "2013-11-12",
      title: "Homefront",
      video: false,
      vote_average: 6.944,
      vote_count: 3117,
      character: "Phil Broker",
      credit_id: "52fe4cecc3a368484e1cd19f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/fGVU8i7hYFgrYO8BzRQIOogKNcg.jpg",
      genre_ids: [53, 80, 28],
      id: 265208,
      original_language: "en",
      original_title: "Wild Card",
      overview: "When a Las Vegas bodyguard with lethal skills and a gambling problem gets in trouble with the mob, he has one last play… and it's all or nothing.",
      popularity: 31.49,
      poster_path: "/zN80Tlly8oMpKbVJv2TfRIj8dHG.jpg",
      release_date: "2015-01-14",
      title: "Wild Card",
      video: false,
      vote_average: 5.639,
      vote_count: 1588,
      character: "Nick Wild",
      credit_id: "534febb30e0a267eaf00109a",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/2uSCHUsmzb6KkQPFSxBQ7bgfJLE.jpg",
      genre_ids: [28, 878, 27],
      id: 345940,
      original_language: "en",
      original_title: "The Meg",
      overview: "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
      popularity: 166.263,
      poster_path: "/xqECHNvzbDL5I3iiOVUkVPJMSbc.jpg",
      release_date: "2018-08-09",
      title: "The Meg",
      video: false,
      vote_average: 6.222,
      vote_count: 6536,
      character: "Jonas Taylor",
      credit_id: "573b72f79251414e3400002b",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/8U9yGCSAhzSDnVUmIQpFMOIBc6q.jpg",
      genre_ids: [28, 80, 53],
      id: 278924,
      original_language: "en",
      original_title: "Mechanic: Resurrection",
      overview:
        "Arthur Bishop thought he had put his murderous past behind him when his most formidable foe kidnaps the love of his life. Now he is forced to travel the globe to complete three impossible assassinations, and do what he does best, make them look like accidents.",
      popularity: 47.321,
      poster_path: "/h651SE7s5z9hbKDiwn38Iubkz5w.jpg",
      release_date: "2016-08-25",
      title: "Mechanic: Resurrection",
      video: false,
      vote_average: 5.962,
      vote_count: 3013,
      character: "Arthur Bishop",
      credit_id: "57cdc61dc3a36867dd000291",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/jT3qYmarKthWD5CRxcwqZiQ1dMI.jpg",
      genre_ids: [28, 12, 80, 53],
      id: 637649,
      original_language: "en",
      original_title: "Wrath of Man",
      overview:
        "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
      popularity: 175.361,
      poster_path: "/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
      release_date: "2021-04-22",
      title: "Wrath of Man",
      video: false,
      vote_average: 7.673,
      vote_count: 4485,
      character: "H",
      credit_id: "5d9b8d9135a61e002223556d",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/7TdVWAO7vV9j1OLDq1hQJS3pb4U.jpg",
      genre_ids: [28, 35, 12, 53],
      id: 739405,
      original_language: "en",
      original_title: "Operation Fortune: Ruse de Guerre",
      overview: "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
      popularity: 81.55,
      poster_path: "/uo7vWfQUlVwueYTDRicXOJa8Oow.jpg",
      release_date: "2023-01-04",
      title: "Operation Fortune: Ruse de Guerre",
      video: false,
      vote_average: 6.599,
      vote_count: 876,
      character: "Orson Fortune",
      credit_id: "5f5162b75aadc400346644d5",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/Aukfa8dk6B5OxuelbaPBOJYXaBI.jpg",
      genre_ids: [28, 878, 27],
      id: 615656,
      original_language: "en",
      original_title: "Meg 2: The Trench",
      overview: "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
      popularity: 198.797,
      poster_path: "/uvYbo4eF3q6W06kpx5iDwC4jt6N.jpg",
      release_date: "2023-08-02",
      title: "Meg 2: The Trench",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "Jonas Taylor",
      credit_id: "5f93b1997719d751dbe9160c",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [80, 53, 18],
      id: 524660,
      original_language: "en",
      original_title: "Small Dark Look",
      overview: "An undercover Russian agent who has risen to become the trusted lieutenant of a London mafia boss is instructed to assassinate one of his fellow countrymen.",
      popularity: 1.42,
      poster_path: null,
      release_date: "",
      title: "Small Dark Look",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "",
      credit_id: "5fc825dc68188800411df751",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 53],
      id: 866398,
      original_language: "en",
      original_title: "The Beekeeper",
      overview: "The film will follow a man’s campaign for vengeance after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      popularity: 1.126,
      poster_path: "/3Jrocls3FqACMRvPL87QLKs1Upj.jpg",
      release_date: "",
      title: "The Beekeeper",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "",
      credit_id: "6129889455c92600639df293",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/qFscHmZExLNAtytSuGCozEHB9k4.jpg",
      genre_ids: [28, 12, 53],
      id: 299054,
      original_language: "en",
      original_title: "Expend4bles",
      overview:
        "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
      popularity: 34.198,
      poster_path: "/nLOw900kDcbvsSs5YshUXRvWS0Z.jpg",
      release_date: "2023-09-21",
      title: "Expend4bles",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "Lee Christmas",
      credit_id: "612d117104b596002a689d40",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 12, 53],
      id: 1141881,
      original_language: "en",
      original_title: "The Expendables 5",
      overview: "Expend4bles is planned as the beginning of a new trilogy, taking the franchise in a new direction",
      popularity: 1.157,
      poster_path: null,
      release_date: "",
      title: "The Expendables 5",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "Lee Christmas",
      credit_id: "648f12e5c2ff3d00ffbbfcb7",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/b5IB4VGjR818tTNcCLHQCIFwQmW.jpg",
      genre_ids: [28, 53],
      id: 10431,
      original_language: "en",
      original_title: "War",
      overview:
        "FBI agent Jack Crawford is out for revenge when his partner is killed and all clues point to the mysterious assassin Rogue. But when Rogue turns up years later to take care of some unfinished business, he triggers a violent clash of rival gangs. Will the truth come out before it's too late? And when the dust settles, who will remain standing?",
      popularity: 33.599,
      poster_path: "/scFc8RD4sFxB2x0eIOaymphMnYh.jpg",
      release_date: "2007-08-24",
      title: "War",
      video: false,
      vote_average: 6.279,
      vote_count: 1499,
      character: "Special Agent Jack Crawford",
      credit_id: "52fe436f9251416c7501035b",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/yZzPTih3HQZUBghrWirt0Rk17uE.jpg",
      genre_ids: [28, 878, 53],
      id: 10796,
      original_language: "en",
      original_title: "The One",
      overview: "A sheriff's deputy fights an alternate universe version of himself who grows stronger with each alternate self he kills.",
      popularity: 17.652,
      poster_path: "/gcr3t71KmeXINemMrhaGBGVJPwW.jpg",
      release_date: "2001-11-02",
      title: "The One",
      video: false,
      vote_average: 6.112,
      vote_count: 1384,
      character: "MVA Agent Evan Funsch",
      credit_id: "52fe43b89251416c7501b909",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/tMpeVt7T2S2NaeEaNCUunCm7laX.jpg",
      genre_ids: [53, 12, 28],
      id: 27578,
      original_language: "en",
      original_title: "The Expendables",
      overview:
        "Barney Ross leads a band of highly skilled mercenaries including knife enthusiast Lee Christmas, a martial arts expert Yin Yang, heavy weapons specialist Hale Caesar, demolitionist Toll Road, and a loose-cannon sniper Gunner Jensen. When the group is commissioned by the mysterious Mr. Church to assassinate the dictator of a small South American island, Barney and Lee visit the remote locale to scout out their opposition and discover the true nature of the conflict engulfing the city.",
      popularity: 62.393,
      poster_path: "/tDynwDj3pvexrEQ8wb0uy8EdcGQ.jpg",
      release_date: "2010-08-03",
      title: "The Expendables",
      video: false,
      vote_average: 6.22,
      vote_count: 7069,
      character: "Lee Christmas",
      credit_id: "52fe4555c3a368484e0541b9",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/41QdmNKbwmVD7R6A7hMqMe9FYMy.jpg",
      genre_ids: [28, 12, 53],
      id: 76163,
      original_language: "en",
      original_title: "The Expendables 2",
      overview: "Mr. Church reunites the Expendables for what should be an easy paycheck, but when one of their men is murdered on the job, their quest for revenge puts them deep in enemy territory and up against an unexpected threat.",
      popularity: 48.368,
      poster_path: "/4EBO8aIeP2bF1jGpwbuRS4CFMca.jpg",
      release_date: "2012-08-08",
      title: "The Expendables 2",
      video: false,
      vote_average: 6.318,
      vote_count: 6168,
      character: "Lee Christmas",
      credit_id: "52fe4929c3a368484e11d76d",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 145308,
      original_language: "en",
      original_title: "Inferno: The Making of 'The Expendables'",
      overview: 'Sylvester Stallone\'s 90-minute video diary, covering the making of "The Expendables".',
      popularity: 3.175,
      poster_path: "/ejMVMjjd7XPjfLDmf78vV3VNoYt.jpg",
      release_date: "2010-11-14",
      title: "Inferno: The Making of 'The Expendables'",
      video: true,
      vote_average: 8.5,
      vote_count: 11,
      character: "Self",
      credit_id: "52fe4b569251416c750ffc33",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/sJDBJxKWG7h3VpG6jc9Mm9bw4kG.jpg",
      genre_ids: [28, 12, 53],
      id: 138103,
      original_language: "en",
      original_title: "The Expendables 3",
      overview:
        "Barney, Christmas and the rest of the team comes face-to-face with Conrad Stonebanks, who years ago co-founded The Expendables with Barney. Stonebanks subsequently became a ruthless arms trader and someone who Barney was forced to kill… or so he thought. Stonebanks, who eluded death once before, now is making it his mission to end The Expendables -- but Barney has other plans. Barney decides that he has to fight old blood with new blood, and brings in a new era of Expendables team members, recruiting individuals who are younger, faster and more tech-savvy. The latest mission becomes a clash of classic old-school style versus high-tech expertise in the Expendables’ most personal battle yet.",
      popularity: 64.315,
      poster_path: "/d63qz4XeNtbpDC5c70AlSUIbnTQ.jpg",
      release_date: "2014-08-07",
      title: "The Expendables 3",
      video: false,
      vote_average: 6.219,
      vote_count: 4493,
      character: "Lee Christmas",
      credit_id: "52fe4c3fc3a368484e1aeb61",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/a0jJMlI1Nw83EXaYmN0QHuccRXm.jpg",
      genre_ids: [28, 35, 80],
      id: 238713,
      original_language: "en",
      original_title: "Spy",
      overview: "A desk-bound CIA analyst volunteers to go undercover to infiltrate the world of a deadly arms dealer, and prevent diabolical global disaster.",
      popularity: 29.15,
      poster_path: "/6On9Ed52fz8W1h9PzaDQ12ZfHdn.jpg",
      release_date: "2015-05-06",
      title: "Spy",
      video: false,
      vote_average: 6.83,
      vote_count: 5588,
      character: "Rick Ford",
      credit_id: "52fe4e83c3a36847f82953ad",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
      genre_ids: [28, 80, 53],
      id: 337339,
      original_language: "en",
      original_title: "The Fate of the Furious",
      overview: "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
      popularity: 85.824,
      poster_path: "/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
      release_date: "2017-04-12",
      title: "The Fate of the Furious",
      video: false,
      vote_average: 6.891,
      vote_count: 9569,
      character: "Deckard",
      credit_id: "5595cbda9251414e06000173",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 357659,
      original_language: "en",
      original_title: "Making 'Snatch'",
      overview: "The making of Guy Ritchie's 'Snatch'.",
      popularity: 1.905,
      poster_path: "/hDpAqVdBVAjRepOHGn1EngI8FSH.jpg",
      release_date: "2001-07-03",
      title: "Making 'Snatch'",
      video: false,
      vote_average: 6.4,
      vote_count: 13,
      character: "Himself",
      credit_id: "55e75eda9251416c120008b8",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
      genre_ids: [28, 12, 35],
      id: 384018,
      original_language: "en",
      original_title: "Fast & Furious Presents: Hobbs & Shaw",
      overview:
        "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have traded smack talk and body blows. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, they join forces to defeat him.",
      popularity: 117.436,
      poster_path: "/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
      release_date: "2019-08-01",
      title: "Fast & Furious Presents: Hobbs & Shaw",
      video: false,
      vote_average: 6.866,
      vote_count: 6466,
      character: "Deckard Shaw",
      credit_id: "59e392f49251410b67000243",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/uqchYxRnt7QRRRPa6Dm5NFigDXW.jpg",
      genre_ids: [18, 28, 10749],
      id: 7515,
      original_language: "en",
      original_title: "London",
      overview: "London is a drug laden adventure that centers on a party in a New York loft where a young man is trying to win back his ex-girlfriend.",
      popularity: 12.138,
      poster_path: "/gCxDOdb9LnL1i3d53vV6DjaembV.jpg",
      release_date: "2005-09-03",
      title: "London",
      video: false,
      vote_average: 6,
      vote_count: 260,
      character: "Bateman",
      credit_id: "52fe4481c3a36847f809a32b",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/y3qcx5YQgAhzC1b6DwdkE1dsFzN.jpg",
      genre_ids: [28, 53],
      id: 9759,
      original_language: "en",
      original_title: "Cellular",
      overview: "A young man receives an emergency phone call on his cell phone from an older woman. She claims to have been kidnapped – and the kidnappers have targeted her husband and child next.",
      popularity: 17.477,
      poster_path: "/AhD3qVfVmxz5CXDxctXwK5nmrOp.jpg",
      release_date: "2004-09-06",
      title: "Cellular",
      video: false,
      vote_average: 6.374,
      vote_count: 1696,
      character: "Ethan",
      credit_id: "52fe4527c3a36847f80bf7d3",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/9h90ga8OYzcHAVHCuwRuFYQQNm.jpg",
      genre_ids: [28, 80, 18],
      id: 9995,
      original_language: "en",
      original_title: "Turn It Up",
      overview:
        "Trying to bootstrap his way out of Brooklyn's mean streets is Diamond, a rap musician. With his long-time pal Gage acting as his manager, he's trying to lay down a demo tape with cut-rate studio time. To pay the bills, he and Gage run drugs for \"Mr. B.\" Inside a week, Diamond's beloved mother dies suddenly, his father appears after an absence of 12 years and wants a relationship, and his girlfriend Kia tells him she's pregnant, asking him if he's ready to be a father. Gage steals $100,000 in a multiple-felony robbery so that Diamond can record a full album, not knowing it's Mr. B's money he's taken. B wants his money, Diamond wants his music, Tia wants an answer.",
      popularity: 3.748,
      poster_path: "/1LqMTyQJnI7IfeDjjGRcDh1vv0r.jpg",
      release_date: "2000-09-06",
      title: "Turn It Up",
      video: false,
      vote_average: 5.1,
      vote_count: 18,
      character: "Mr. B",
      credit_id: "52fe455ac3a36847f80c973b",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/yQMNl71tz59z10wlp0DOL7zUxpU.jpg",
      genre_ids: [18, 53],
      id: 44982,
      original_language: "en",
      original_title: "13",
      overview: "A naive young man assumes a dead man's identity and finds himself embroiled in an underground world of power, violence, and chance where men gamble behind closed doors on the lives of other men.",
      popularity: 15.913,
      poster_path: "/eJAVjARKe3YBabnbhdbYWXD7Hdg.jpg",
      release_date: "2010-03-12",
      title: "13",
      video: false,
      vote_average: 5.793,
      vote_count: 707,
      character: "Jasper",
      credit_id: "52fe46a8c3a36847f810b083",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg",
      genre_ids: [28, 53, 80],
      id: 168259,
      original_language: "en",
      original_title: "Furious 7",
      overview: "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
      popularity: 89.882,
      poster_path: "/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg",
      release_date: "2015-04-01",
      title: "Furious 7",
      video: false,
      vote_average: 7.238,
      vote_count: 9840,
      character: "Deckard Shaw",
      credit_id: "5431dfc70e0a265872002bd5",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/cXQH2u7wUIX1eoIdEj51kHXoWhX.jpg",
      genre_ids: [35, 80],
      id: 100,
      original_language: "en",
      original_title: "Lock, Stock and Two Smoking Barrels",
      overview:
        "A card shark and his unwillingly-enlisted friends need to make a lot of cash quick after losing a sketchy poker match. To do this they decide to pull a heist on a small-time gang who happen to be operating out of the flat next door.",
      popularity: 11.42,
      poster_path: "/8kSerJrhrJWKLk1LViesGcnrUPE.jpg",
      release_date: "1998-08-28",
      title: "Lock, Stock and Two Smoking Barrels",
      video: false,
      vote_average: 8.13,
      vote_count: 5962,
      character: "Bacon",
      credit_id: "52fe4217c3a36847f8003607",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/anSbunnEMI0TSmizqUSRACoe18l.jpg",
      genre_ids: [28, 27, 878],
      id: 10016,
      original_language: "en",
      original_title: "Ghosts of Mars",
      overview:
        "In 2176, a Martian police unit is sent to pick up a highly dangerous criminal at a remote mining post. Upon arrival, the cops find the post deserted and something far more dangerous than any criminal — the original inhabitants of Mars, hellbent on getting their planet back.",
      popularity: 13.752,
      poster_path: "/i2zztssCIbahGES1fdfWFmDXian.jpg",
      release_date: "2001-08-24",
      title: "Ghosts of Mars",
      video: false,
      vote_average: 5.1,
      vote_count: 950,
      character: "Sgt. Jericho Butler",
      credit_id: "52fe43089251416c75000d79",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/7bWa6MjkalUyf6JdOXlCRKbLpS0.jpg",
      genre_ids: [28, 80],
      id: 9654,
      original_language: "en",
      original_title: "The Italian Job",
      overview:
        "Charlie Croker pulled off the crime of a lifetime. The one thing that he didn't plan on was being double-crossed. Along with a drop-dead gorgeous safecracker, Croker and his team take off to re-steal the loot and end up in a pulse-pounding, pedal-to-the-metal chase that careens up, down, above and below the streets of Los Angeles.",
      popularity: 29.389,
      poster_path: "/eSkjK4kctyrWpFhxl35GPvSs6tI.jpg",
      release_date: "2003-05-30",
      title: "The Italian Job",
      video: false,
      vote_average: 6.764,
      vote_count: 5015,
      character: "Handsome Rob",
      credit_id: "52fe4517c3a36847f80bbd4b",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 1048938,
      original_language: "en",
      original_title: "Red Desert Nights: Making Ghosts of Mars",
      overview: "Documentary about the making of John Carpenter's sci-fi horror movie, Ghosts of Mars.",
      popularity: 0.6,
      poster_path: null,
      release_date: "2001-12-04",
      title: "Red Desert Nights: Making Ghosts of Mars",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "Himself",
      credit_id: "6373dc9268ff70007c2a6ab3",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/w3LLngJIAA1R7Mp2S3G0HZl2R3H.jpg",
      genre_ids: [16, 10751],
      id: 45772,
      original_language: "en",
      original_title: "Gnomeo & Juliet",
      overview:
        "A version of Shakespeare's play, set in the world of warring indoor and outdoor gnomes. Garden gnomes Gnomeo and Juliet have as many obstacles to overcome as their quasi namesakes when they are caught up in a feud between neighbors. But with plastic pink flamingos and lawnmower races in the mix, can this young couple find lasting happiness?",
      popularity: 29.489,
      poster_path: "/vVQwgfS9gSFviVT4gS7tZAmhRFc.jpg",
      release_date: "2011-01-13",
      title: "Gnomeo & Juliet",
      video: false,
      vote_average: 5.859,
      vote_count: 1778,
      character: "Tybalt (voice)",
      credit_id: "52fe46d2c3a36847f8114201",
      order: 6,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 80, 53],
      id: 755679,
      original_language: "en",
      original_title: "Fast X: Part 2",
      overview: "The eleventh installment in The Fast Saga.",
      popularity: 66.37,
      poster_path: "/lD8V3DBban95Mxz4sjuA81Tw771.jpg",
      release_date: "2025-04-04",
      title: "Fast X: Part 2",
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: "Deckard Shaw",
      credit_id: "64674918006b01010589771a",
      order: 9,
    },
    {
      adult: false,
      backdrop_path: "/lXwvQ7JEHm5kaHPVm7QR4mAnOkN.jpg",
      genre_ids: [35, 18],
      id: 9991,
      original_language: "en",
      original_title: "Mean Machine",
      overview:
        "Disgraced ex-England football captain, Danny 'Mean Machine' Meehan, is thrown in jail for assaulting two police officers. He keeps his head down and has the opportunity to forget everything and change the lives of the prisoners. When these prisoners have the chance to put one over the evil guards during a prison football match, Danny takes the lead.",
      popularity: 11.51,
      poster_path: "/ripTQsmWQJyccK6zB1dajSY3olv.jpg",
      release_date: "2001-12-26",
      title: "Mean Machine",
      video: false,
      vote_average: 6.246,
      vote_count: 509,
      character: "Monk",
      credit_id: "52fe4559c3a36847f80c92fb",
      order: 11,
    },
    {
      adult: false,
      backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
      genre_ids: [28, 80, 53],
      id: 385687,
      original_language: "en",
      original_title: "Fast X",
      overview:
        "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
      popularity: 4714.532,
      poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
      release_date: "2023-05-17",
      title: "Fast X",
      video: false,
      vote_average: 7.325,
      vote_count: 2337,
      character: "Shaw",
      credit_id: "62ab7a9435a61e0062082a1b",
      order: 14,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 28],
      id: 68996,
      original_language: "en",
      original_title: "Ultimate Fights from the Movies",
      overview:
        "In their second film compilation following their 'Boogeymen:The Killer Compilation' series, FlixMix takes you into the history of action movies from Hollywood to Hong Kong cinema that spans a 20-year period. This one features action scenes from 16 action-packed movies featuring action gurus, Jet Li, Michelle Yeoh, Chow Yun-Fat, Jackie Chan, Jean-Claude Van Damme and many more.",
      popularity: 5.669,
      poster_path: "/zMGmnxe7Lap6Ek1ZxIzdAdbuJeJ.jpg",
      release_date: "2002-04-16",
      title: "Ultimate Fights from the Movies",
      video: true,
      vote_average: 4.8,
      vote_count: 26,
      character: "Turkish (Snatch) (archive footage)",
      credit_id: "52fe47b4c3a368484e0d522b",
      order: 43,
    },
    {
      adult: false,
      backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
      genre_ids: [28, 12, 80],
      id: 385128,
      original_language: "en",
      original_title: "F9",
      overview: "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
      popularity: 111.479,
      poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
      release_date: "2021-05-19",
      title: "F9",
      video: false,
      vote_average: 7.166,
      vote_count: 6477,
      character: "Deckard Shaw (uncredited)",
      credit_id: "60c133baf18ce70029732901",
      order: 43,
    },
    {
      adult: false,
      backdrop_path: "/mRfI3y2oAd7ejur2di09xC9niqp.jpg",
      genre_ids: [28, 53, 80],
      id: 82992,
      original_language: "en",
      original_title: "Fast & Furious 6",
      overview: "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.",
      popularity: 10.548,
      poster_path: "/thSmnRdrzPBBospIOJjLZBReqzo.jpg",
      release_date: "2013-05-21",
      title: "Fast & Furious 6",
      video: false,
      vote_average: 6.817,
      vote_count: 9883,
      character: "Deckard Shaw (uncredited)",
      credit_id: "60b14275945c20005810a7b6",
      order: 44,
    },
    {
      adult: false,
      backdrop_path: "/3jiNJ4lyAmdSidvbFTFIL2GQGBu.jpg",
      genre_ids: [35, 9648, 80, 12, 10751],
      id: 12096,
      original_language: "en",
      original_title: "The Pink Panther",
      overview:
        "When the coach of the France soccer team is killed by a poisoned dart in the stadium in the end of a game, and his expensive and huge ring with the diamond Pink Panther disappears, the ambitious Chief Inspector Dreyfus assigns the worst police inspector Jacques Clouseau to the case.",
      popularity: 19.103,
      poster_path: "/57ViRkdsddHLK32W8Nf3ZPLSAu4.jpg",
      release_date: "2006-02-10",
      title: "The Pink Panther",
      video: false,
      vote_average: 5.827,
      vote_count: 1747,
      character: "Yves Gluant (uncredited)",
      credit_id: "5f56da4c9d89390036d2d4f3",
      order: 50,
    },
    {
      adult: false,
      backdrop_path: "/4Q9UK0Dy32jW9uCs6KQS4hPMA0A.jpg",
      genre_ids: [18, 80, 53],
      id: 1538,
      original_language: "en",
      original_title: "Collateral",
      overview: "Cab driver Max picks up a man who offers him $600 to drive him around. But the promise of easy money sours when Max realizes his fare is an assassin.",
      popularity: 31.559,
      poster_path: "/iOpi3ut5DhQIbrVVjlnmfy2U7dI.jpg",
      release_date: "2004-08-04",
      title: "Collateral",
      video: false,
      vote_average: 7.207,
      vote_count: 4953,
      character: "Man in Airport",
      credit_id: "531e073cc3a3685c37008875",
      order: 60,
    },
  ],
  crew: [
    {
      adult: false,
      backdrop_path: "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
      genre_ids: [28, 12, 35],
      id: 384018,
      original_language: "en",
      original_title: "Fast & Furious Presents: Hobbs & Shaw",
      overview:
        "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have traded smack talk and body blows. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, they join forces to defeat him.",
      popularity: 117.436,
      poster_path: "/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
      release_date: "2019-08-01",
      title: "Fast & Furious Presents: Hobbs & Shaw",
      video: false,
      vote_average: 6.866,
      vote_count: 6466,
      credit_id: "5d459be3a0be280016a2c11f",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/7TdVWAO7vV9j1OLDq1hQJS3pb4U.jpg",
      genre_ids: [28, 35, 12, 53],
      id: 739405,
      original_language: "en",
      original_title: "Operation Fortune: Ruse de Guerre",
      overview: "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
      popularity: 81.55,
      poster_path: "/uo7vWfQUlVwueYTDRicXOJa8Oow.jpg",
      release_date: "2023-01-04",
      title: "Operation Fortune: Ruse de Guerre",
      video: false,
      vote_average: 6.599,
      vote_count: 876,
      credit_id: "60b09b0af29d66005750cb52",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/qFscHmZExLNAtytSuGCozEHB9k4.jpg",
      genre_ids: [28, 12, 53],
      id: 299054,
      original_language: "en",
      original_title: "Expend4bles",
      overview:
        "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
      popularity: 34.198,
      poster_path: "/nLOw900kDcbvsSs5YshUXRvWS0Z.jpg",
      release_date: "2023-09-21",
      title: "Expend4bles",
      video: false,
      vote_average: 0,
      vote_count: 0,
      credit_id: "612d128ea13533004213ffd3",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 53],
      id: 866398,
      original_language: "en",
      original_title: "The Beekeeper",
      overview: "The film will follow a man’s campaign for vengeance after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      popularity: 1.126,
      poster_path: "/3Jrocls3FqACMRvPL87QLKs1Upj.jpg",
      release_date: "",
      title: "The Beekeeper",
      video: false,
      vote_average: 0,
      vote_count: 0,
      credit_id: "621353ffdfe31d006e38861b",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/Aukfa8dk6B5OxuelbaPBOJYXaBI.jpg",
      genre_ids: [28, 878, 27],
      id: 615656,
      original_language: "en",
      original_title: "Meg 2: The Trench",
      overview: "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
      popularity: 198.797,
      poster_path: "/uvYbo4eF3q6W06kpx5iDwC4jt6N.jpg",
      release_date: "2023-08-02",
      title: "Meg 2: The Trench",
      video: false,
      vote_average: 0,
      vote_count: 0,
      credit_id: "64598c7d1b70ae01260c9b54",
      department: "Production",
      job: "Executive Producer",
    },
  ],
  id: 976,
};
